name: Publish NuGet

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Validate"]
    branches: [main]
    types: [completed]

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required to fetch the OIDC token
      contents: read     # Required to checkout repository code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.x
            8.0.x

      - name: Restore dependencies
        run: dotnet restore *.slnx

      - name: Build solution
        run: dotnet build *.slnx --no-restore --configuration Release

      - name: Build NuGet package
        run: dotnet pack *.slnx --no-build --configuration Release --output ./nuget

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push nuget/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
